version: '3.3'

services:

  web:
    container_name: payoff_web
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn chartJsProject.wsgi:application --timeout 2400 --bind 0.0.0.0:8000      
    # command: python manage.py runserver 0.0.0.0:8000  
    volumes:
      - .:/code
    expose:
      - 8000
    # ports:
    #   - "8001:8000"
    env_file:
      - ./.env.prod
    networks:
      rob_network:
        ipv4_address: 172.18.0.101

networks:
  rob_network:
    external:
      name: docker-db_rede