# Generated by Django 4.0.4 on 2022-04-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ativo', models.CharField(max_length=10)),
                ('valor_strike', models.FloatField()),
                ('vencimento', models.DateField()),
                ('am_europeia', models.CharField(max_length=2)),
                ('on_pn', models.CharField(max_length=2)),
                ('call_put_papel', models.CharField(max_length=2)),
                ('formador_mercado', models.CharField(max_length=2)),
                ('empresa', models.CharField(max_length=18)),
                ('data_criacao_tabela', models.DateTimeField()),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bid', models.FloatField()),
                ('valor_ask', models.FloatField()),
                ('data_hora_cotacao', models.DateTimeField()),
                ('valor_cotacao_papel_instante', models.FloatField()),
                ('nome_ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.FloatField()),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.cotacao')),
                ('nome_ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.ativo')),
            ],
        ),
    ]
