# Generated by Django 4.0.4 on 2022-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_ativo_cotacao_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='empresa',
            field=models.CharField(default='Petrobras', max_length=18),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='formador_mercado',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='habilitado',
            field=models.BooleanField(default='true'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='on_pn',
            field=models.CharField(default='PN', max_length=2),
        ),
    ]
