# Generated by Django 4.0.4 on 2022-04-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_ativo_empresa_alter_ativo_formador_mercado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='ativo',
            name='formador_mercado',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
